console.log("Introduçao OO:")
console.log("O curso entra no capítulo de Objetos: antes funções manipulavam dados, agora os dados (objetos) possuem funções e atributos.")
 console.log(" A POO se baseia em 4 pilares: Abstração, Encapsulamento, Herança e Polimorfismo.");
console.log(" Primeiro é preciso entender os fundamentos para depois aplicar em projetos reais.")
// CÓDIGO NÃO EXCUTÁVEL!!
 //Procedural:
  processamento(valor1, valor2, valor3)
 // OO
 objeto = {
     valor1,
     valor2,
     valor3,
     processamento() {
        //---- 
     }
 }
// objeto.processamento() // foco passou a ser o objeto
 //Principios Importantes:
 // 1ª abstacao;
 // 2ª encapsulamento;
 // 3ª herança(prototype)
 // 4ª polimorfismo 

 console.log("The End")