console.log("Visão Geral Estruturas de Dados")
console.log("Explica...o que são Geral Estruturas de Dados? Trazer ordem aos dados...")
console.log("Ex.: saiu a lista de aprovados")
console.log("FIFO")
console.log("LIFO")
console.log("ARVORE")
console.log("TABELAS")
console.log("Estruturas de Dados Básicas:")
console.log("-> INT/REAL/LETRA/BOOL")
console.log("The End")